<header>
    <!--<h1>EDC IT Solutions</h1> -->
    <img src="images/logo3.svg" alt="Logo" class="logo">
    <nav>
        <ul>
            <li><a href="index.php">Home🏡</a></li>
            <li><a href="jobs.php">Jobs⚒️</a></li>
            <li><a href="apply.php">Apply✅</a></li>
            <li><a href="about.php">About👯</a></li>
            <li><a href="mailto:charliewalker@gmail.com">Email📩</a></li>
        </ul>
    </nav>
</header>