<header>
    <!--<h1>EDC IT Solutions</h1> -->
    <img src="images/logo3.svg" alt="Logo" class="logo">
    <nav>
        <ul>
            <li><a href="index.html">Home🏡</a></li>
            <li><a href="jobs.html">Jobs⚒️</a></li>
            <li><a href="apply.html">Apply✅</a></li>
            <li><a href="about.html">About👯</a></li>
            <li><a href="mailto:charliewalker@gmail.com">Email📩</a></li>
        </ul>
    </nav>
</header>